<?php get_template_part('block','header'); ?>
<?php the_post(); ?>

<main id="legal">
	<div class="container">
		<h1 class="headline">Privacy Policy</h1>
<p>Effective as of March 11, 2019.</p>
<p>This privacy policy addresses how this website and all pages within this website located at <a href="https://omaxhealth.com" target="_blank">omaxhealth.com</a> (this "Site") and its owner, Omax Health, Inc. (“Company”) collect and use information you provide. By visiting this Site, and providing your information to us, you agree to accept the practices described in this privacy policy.</p>
<p><strong>WHAT INFORMATION WE COLLECT ABOUT YOU</strong></p>
<p>We group the collection of user information into two categories: personal, which is information identifiable to a specific member, and aggregate, which is general demographic information that does not identify any individual member. Personal information may include your name, email address, mailing address, credit card information and phone number. We may also collect certain demographic information such as your site preferences, age, gender, geographical location, language, time zone, income and education (some of the information we ask for may be optional). Company may use or disclose aggregate information for any purpose.</p>
<p><strong>HOW YOUR INFORMATION MAY BE USED</strong></p>
<p>We collect personal information to make our services related to this Site ("Services") more rewarding for you to use, including billing, shipping and tracking your orders. If we have any questions or concerns regarding your order, we may use this information to contact you. We also use this information for internal purposes, such as studying our customers' preferences and improving the customers' experiences. We may also use your information to contact you for promotional purposes. We also may use this information to provide customer service to you. If you enter into a sweepstakes, contest, or similar promotion, we may use the information you provide to administer those activities. We may combine information about you with information from other sources in order to improve the quality of our services.</p>
<p>We also receive and store certain personally non-identifiable information, which is collected passively using various technologies, and cannot presently be used to specifically identify you. This Site may use such information and pool it with other information to track, for example, the total number of visitors to our Site, the number of visitors to each page of our Site, the domain names of our visitors' Internet service providers, and how our users use and interact with the Services.</p>
<p>Also, in an ongoing effort to better understand and serve you, we often conduct research on customer demographics, interests and behavior based on the personal information and other information provided to us. This research may be compiled and analyzed on an aggregate basis. We may share this non-identifiable and aggregate data with affiliates, agents and business partners, but this type of non-identifiable and aggregate information does not identify you personally. We may also disclose aggregated user statistics in order to describe our Services to current and prospective business paSS rtners, and to other third parties for other lawful purposes.</p>
<p><strong>HOW YOUR INFORMATION IS SHARED</strong></p>
<p>There are certain circumstances in which we may share your personal information with certain third parties without further notice to you, as set forth below:</p>
<ul style="margin: 0px 50px;">
<li>We may share information about you with trusted third parties to improve your consumer experience. These third parties may contact you about products, services or promotions you may be interested in, or to otherwise improve your customer experience with this Site.</li>
<li>As we develop our business, we might sell or buy businesses or assets. In the event of a corporate sale, merger, reorganization, dissolution or similar event, your information may be part of the transferred assets.</li>
<li>When we believe in good faith that disclosure is necessary to protect the rights, property and safety of Company’s products, product users, or the public.</li>
<li>As required by law, to comply with a judicial proceeding or court order, to exercise our rights, or to defend against any claims.</li>
</ul>
<p><strong>ECOMMERCE</strong></p>
<p>Our store is hosted on a third-party e-commerce platform that allows us to sell our products and services to you. Your data is stored through their data storage, databases and the general application. They store your data on a secure server behind a firewall.</p>
<p><strong>PAYMENT</strong></p>
<p>Your purchase is encrypted through the Payment Card Industry Data Security Standard (PCI-DSS). Your purchase transaction data is stored only as long as is necessary to complete your purchase transaction. After that is complete, your purchase transaction information is deleted.</p>
<p>All payment gateways we use adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of credit card information by our store and its service providers.</p>
<p><strong>THIRD-PARTY SERVICES</strong></p>
<p>In general, the third-party providers used by us will only collect, use and disclose your information to the extent necessary to allow them to perform the services they provide to us.</p>
<p>However, certain providers may be in or have facilities that are located in a different jurisdiction than either you or us. So, if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.</p>
<p>As an example, if you are in Canada, and your transaction is processed our payment gateway located in the United States, then your personal information used in completing that transaction may be subject to disclosure under United States legislation, including the Patriot Act.</p>
<p>Once you leave our store’s website or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy or our website’s Terms of Service.</p>
<p><strong>SECURITY</strong></p>
<p>The security of your personal information is important to us. When you provide sensitive information (such as a credit card number), we encrypt that information using secure socket layer technology (SSL). We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee the absolute security of such information. If you have any questions about security on our Site, please contact us as indicated below.</p>
<p><strong>COOKIES</strong></p>
<p>A cookie is a small text file that is stored on a user's computer for record-keeping purposes. We use cookies to collect anonymous information about how you use this Site by setting and accessing cookies on your computer. These cookies track information such as how often you visit our Site, what pages you view, and where you go after you leave our Site. The cookies are not connected to your personal information. We recommend that you leave cookies turned on because they allow you to take advantage of some of this Site's features.</p>
<p><strong>WEB BEACONS</strong></p>
<p>Web beacons, or clear gifs, are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of web users. In contrast to cookies, which are stored on a user's computer hard drive, web beacons are embedded invisibly on web pages. Web beacons help us better manage content on our Site by informing us what content is effective. We do not tie the information gathered by web beacons to your personal information.</p>
<p><strong>OPTING OUT</strong></p>
<p>We may occasionally send you newsletters and emails regarding special offers, promotions, features and/or product updates. We may also communicate with you on behalf of third parties about special offers, promotions, features and/or product updates we think may be of interest to you, or you may have opted-in to receive newsletters or special promotions from one of our trusted third party providers. If you decide you do not wish to receive these communications, you may opt-out by clicking the unsubscribe link or by following the instructions included in the communication. Note however that as user of the Site you cannot opt-out of some administrative communications that are reasonably necessary to the Site, such as billing or service notifications.</p>
<p><strong>LINKS TO OTHER SITES</strong></p>
<p>This Site may contain links to other sites that are not owned or controlled by us. Please be aware that we are not responsible for the privacy practices of such other sites. This privacy statement applies only to information collected by this Site. We encourage you to be aware when you leave our Site and to read the privacy statements of each and every website that collects personally identifiable information. This Privacy Policy does not cover any information that you disclose to such sites or that they may collect. The privacy policies of these other sites may be significantly different from this Privacy Policy. We are not responsible for the privacy practices of these other sites and cannot guarantee the security of any of your personal information collected there. This Site may enable you to post comments, reviews and other information on publicly available areas of this Site. Any information you post in these areas of this Site will be available to all of our users, so please use caution in disclosing any personal information when you post such comments, reviews or other information.</p>
<p><strong>SMS/MMS MOBILE MESSAGING MARKETING PROGRAM</strong></p>
<p>We respect your privacy. We will only use information you provide through the Program to transmit your mobile messages and respond to you, if necessary. This includes, but is not limited to, sharing information with platform providers, phone companies, and other vendors who assist us in the delivery of mobile messages. WE DO NOT SELL, RENT, LOAN, TRADE, LEASE, OR OTHERWISE TRANSFER FOR PROFIT ANY PHONE NUMBERS OR CUSTOMER INFORMATION COLLECTED THROUGH THE PROGRAM TO ANY THIRD PARTY. Nonetheless, We reserve the right at all times to disclose any information as necessary to satisfy any law, regulation or governmental request, to avoid liability, or to protect Our rights or property. When you complete forms online or otherwise provide Us information in connection with the Program, you agree to provide accurate, complete, and true information. You agree not to use a false or misleading name or a name that you are not authorized to use. If, in Our sole discretion, We believe that any such information is untrue, inaccurate, or incomplete, or you have opted into the Program for an ulterior purpose, We may refuse you access to the Program and pursue any appropriate legal remedies.</p>
<p>California Civil Code Section 1798.83 permits Users of the Program that are California residents to request certain information regarding our disclosure of the information you provide through the Program to third parties for their direct marketing purposes. To make such a request, please contact us at the following address:</p>
<p>Omax Health, Inc.<br /> 2601 Ocean Park Blvd. Unit 214<br /> Santa Monica, CA 90405<br /> <a href="mailto:care@omaxhealth.com">care@omaxhealth.com</a></p>
<p>This Privacy Policy is strictly limited to the Program and has no effect on any other privacy policy(ies) that may govern the relationship between you and Us in other contexts.</p>
<p><strong>FACEBOOK</strong></p>
<p>You can log in to your Account using your Facebook account, or utilize your Facebook account to access and use the social features on this Site. In doing so, Facebook will ask your permission to share certain information from your Facebook account with this Site. This may include your first name, last name, gender, profile picture, list of friends, a link to your Facebook profile, likes, and other data that is part of your or your friends' Facebook profile(s). Facebook collects this information and provides it to Company under the terms of Facebook's Privacy Policy. You can control the information that Company receives from Facebook using the privacy settings in your Facebook account. If you use your Facebook account to access and use the social features on this Site, your Facebook user name and your Facebook profile picture will be shared with other users of this Site. Further, other users of this Site may be able to view your profile and shopping activity on this Site.</p>
<p>You may choose to share your shopping activity on this Site with your friends on Facebook. A subset of your user activity on this Site, including your likes, purchases, wish lists and friends, will automatically be shared to both your friends on Facebook and with your Facebook friends on this Site. Additionally, such activity will be visible to users on this Site who have a Facebook account but who might not be your friend on Facebook. The information you choose to share with your Facebook friends will be attributed to your Facebook account that was used to access this Site. Facebook's use of such information and any information it collects from your use of Facebook is governed by Facebook's Privacy Policy. Company has no liability or responsibility for the privacy practices or other actions of Facebook that may be enabled within use of this Site. The use of information on this Site is governed by this Site's Privacy Policy. You understand and acknowledge that you have read and are familiar with this Site's Privacy Policy and Facebook's Privacy Policy. If you do not wish to share your activity on this Site with your friends on Facebook, you may adjust your sharing settings on this Site at any time to disable such sharing. You understand and acknowledge that if you adjust your settings to disable such sharing on Facebook, such activity may continue to be publicly available to other users on this Site, including users with Facebook accounts.</p>
<p><strong>UPDATING OR DELETING YOUR ONLINE ACCOUNT INFORMATION</strong></p>
<p>You may update or correct your online account information at any time by logging into your account and navigating to the "My Account" page or by contacting us. You can also contact us by phone if you wish to deactivate your account, but note that we may retain certain information as required by law or for legitimate business purposes. We may also retain cached or archived copies of information about you for a certain period.</p>
<p><strong>CHILDREN UNDER 18</strong></p>
<p>Children under 18 may view this Site, but they cannot make a purchase or provide any personal information. This Site is not designed for children and we do not wish to collect personal information from children under 18. If you register with us and we discover that you are under 18, we will delete your account.</p>
<p><strong>EXCLUSION TO THIS PRIVACY POLICY</strong></p>
<p>This Privacy Policy shall not apply to any unsolicited information you provide to Company through this Site or through any other means. This includes, but is not limited to, information posted to any public areas of the Site, such as review sections and forums (collectively, "Public Areas"), any ideas for new products or modifications to existing products, and other unsolicited submissions (collectively, "Unsolicited Information"). All Unsolicited Information shall be deemed to be non-confidential and Company shall be free to reproduce, use, disclose, distribute and exploit such Unsolicited Information without limitation or attribution.</p>
<p><strong>AMENDMENTS OR MODIFICATIONS TO THIS POLICY</strong></p>
<p>We reserve the right to amend this policy at any time without prior notice. Notice of any change will be posted on this Site. Please check this page periodically for changes. Your continued use of the Site after any changes or revisions to this Privacy Policy shall indicate your agreement with the terms of such revised Privacy Policy.</p>
<p><strong>CONTACT US</strong></p>
<p>If you would like to access, correct, amend or delete any personal information we have about you, please contact us at:</p>
<p>Omax Health, Inc.<br /> 2601 Ocean Park Blvd, Ste 214<br /> Santa Monica, CA 90405<br /> USA</p>
<p>You can email us at <a href="mailto:care@omaxhealth.com">care@omaxhealth.com</a> or contact our customer service representatives, Mon-Fri, 8am to 7pm EST, by calling 1-800-765-6691</p>
<p>© Omax Health, Inc. <script>document.write(new Date().getFullYear())</script></p>
<p> </p>
	</div>
</main>

<?php get_template_part('block','footer'); ?>