<?php get_template_part('block','header'); ?>
<?php the_post(); ?>

<main id="legal">
	<div class="container">
			<h1 class="headline">Terms &amp; Conditions</h1>

<p>Effective as of March 11, 2019.</p>
<p>This website and all pages within this website located at <a href="https://omaxsleep.com" target="_blank">omaxsleep.com</a> (this "Site") is owned and operated by Omax Health, Inc. ("Company") and provides website features and other products and services to you when you visit, shop or purchase items from this Site, use or access this Site from your mobile devices, or use software. By using Company’s products and services, including Omax3 properties, you agree to these conditions. Please read them carefully. You should also carefully review our Privacy Policy before placing an order for goods or services through this site. By placing an order on our site, you are agreeing to an arbitration clause below.</p>
<p>By accessing or using this Site, mobile application or other Company product or service on any computer, mobile phone, tablet, console or other device (collectively, "Device"), or by any other means, you acknowledge and agree that you have read, understand and agree to be bound by these Terms and Conditions and by any applicable law.</p>
<p>Company may change these Terms and Conditions at any time without notice. When we make changes, we will post them here. If you do not agree to these Terms and Conditions, please do not use this Site or any Company products or services, and please promptly exit this Site.</p>

<p><strong>SINGLE-BOX SUBSCRIBE AND SAVE</strong></p>
<p>Pay $39.95 today for a 1-month supply (1, 60 count box) of Omax Sleep & Stress Remedy (A $59.95 retail value) and you'll receive free shipping and our 60-day money back guarantee.* As a VIP member, in 30 days and every 60 days thereafter you will receive an auto-shipment for a 2-month supply, billed to your credit card for $79.99. You can call customer service at any time to cancel, skip or change your auto-shipments.</p>

<p><strong>SINGLE-BOX ONE-TIME SHIPMENT</strong></p>
<p>Pay $59.95 for a 1-month supply (1, 60 count box) of Omax Sleep & Stress Remedy.</p>
<p>*60-day money back guarantee applies to your first order of Omax Sleep & Stress Remedy, less return shipping & handling fees.</p>

<p><strong>3-BOX SUBSCRIBE AND SAVE</strong></p>
<p>Pay $109.95 today for a 3-month supply (3, 60 count boxs) of Omax Sleep & Stress Remedy (A $179.85 retail value) and you'll receive free shipping and our 60-day money back guarantee.* As a VIP member, in 90 days and every 90 days thereafter you will receive an auto-shipment for a 3-month supply, billed to your credit card for $109.99. You can call customer service at any time to cancel, skip or change your auto-shipments.</p>

<p>This website and all pages within this website located at <a target="_blank" href="http://omaxsleep.com">omaxsleep.com</a> (this "Site") is owned and operated by Omax Health, Inc. f/k/a Prevention Pharmaceuticals, Inc. ("Company") and provides website features and other products and services to you when you visit, shop or purchase items from this Site, use or access this Site from your mobile devices, or use software. By using Company's products and services, including Omax3 properties, you agree to these conditions. Please read them carefully. You should also carefully review our <a href="<?php bloginfo('url'); ?>/privacy-policy/" title="Privacy Policy">Privacy Policy</a> before placing an order for goods or services through this site. <strong>By placing an order on our site, you are agreeing to an arbitration clause below. </strong></p>

<p>By accessing or using this Site, mobile application or other Company product or service on any computer, mobile phone, tablet, console or other device (collectively, "Device"), or by any other means, you acknowledge and agree that you have read, understand and agree to be bound by these Terms and Conditions and by any applicable law.</p>
<p>Company may change these Terms and Conditions at any time without notice. When we make changes, we will post them here. If you do not agree to these Terms and Conditions, please do not use this Site or any Company products or services, and please promptly exit this Site.</p>

<p><strong>ELECTRONIC COMMUNICATIONS</strong></p>
<p>When you use any Site service, or send e-mail messages to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this Site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
<p>You expressly consent and request to be contacted by members of our network by phone, email, text/SMS, and through the use of an automatic telephone dialing systems and pre-recorded messages at the number(s) listed on the form submitted even if your number provided on the form is on a National or State Do Not Call List. In some cases, automated technology may be used to contact you including on your cellular telephone for promotional messages. Your consent does not require you to purchase any goods and/or services &amp; you have clicked, read &amp; agree to the privacy terms located at the bottom of this page. Standard carrier and messaging rates will apply. Reply "Help" for help or "Stop".</p>
<p><strong>ORDER ACCEPTANCE AND CANCELLATION</strong></p>
<p>Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does it constitute confirmation of our offer to sell. We reserve the right at any time after receipt of your order to accept, decline, or limit your order for any reason, whether your credit card has been charged or not. We reserve the right at any time after receipt of your order, without prior notice to you, to supply less than the quantity you ordered of any item. In all cases, if your credit card has been charged and your order is cancelled you will receive a prompt refund credit to your account.</p>
<p>Once an order has been placed, it cannot be cancelled unless the shipment is unavoidably delayed. In this case, we will do our best to cancel the order if requested.</p>
<p>We are a reseller to end user customers and do not accept orders from dealers, exporters, wholesalers, or other customers who intend to resell the products on our website. We have a limit of 12 boxes on Omax3 Ultra-Pure and Omax Cognitive Boost for this reason and to ensure you receive the freshest product. Should we determine or suspect that you are purchasing orders from our site for purposes of resale, without our consent, we reserve the right to stop selling to you. We take fraud very seriously and have fraud protection systems in place. Should your order be flagged for fraud, it will automatically be cancelled and refunded to your credit card. We make every effort to maintain the availability of our site. However, should we experience technical difficulties, we are not responsible for orders that are not processed or accepted.</p>
<p><strong>BLACK FRIDAY</strong></p>
<p>Promotion ends on 12/1 at 11:59pm. Does not apply to any Omax3 Ultra-Pure, Omax3 Professional Strength, or Subscribe &amp; Save shipments. Cannot be combined with any other discount code. Free shipping applies to contiguous U.S.</p>
<p><strong>CYBER MONDAY</strong></p>
<p>Promotion ends on 12/2 at 11:59pm. Does not apply to any Omax3 Ultra-Pure, Omax3 Professional Strength, or Subscribe &amp; Save shipments. Cannot be combined with any other discount code. Free shipping applies to contiguous U.S.</p>
<p><strong>SHIPPING</strong></p>
<p>Shipping and handling fees are as follows. Company reserves the right to use any shipping service we choose to ship products to you. We offer ground and rush shipping options.</p>
<p>Hemp products are currently not available for shipping outside of the 48 Contiguous U.S.</p>
<p>48 CONTIGUOUS U.S.</p>
<p>Ground: $7.95 (7-10 business days)</p>
<p>Rush: $15.95 (3-5 business days)</p>
<p>We also ship to: Alaska, Hawaii, Puerto Rico, Guam, Northern Mariana Islands, U.S. Virgin Islands, and American Samoa, and Canada. Orders shipping to Canada are currently $29.95 through UPS service with tracking. All other orders will incur an additional surcharge of $9.95.</p>
<p>*All delivery times above are based on average in-transit time, after the order has been processed by our fulfillment warehouse. Orders are processed during EST business hours Monday - Friday.</p>
<p>All shipping prices are quoted in United States dollars. No C.O.D. orders can be accepted.</p>
<p>The posted shipping time frame is contingent upon credit card approval and may be delayed should we experience difficulties in obtaining authorization or during holidays.</p>
<p>There may be occasional delays beyond the posted order processing time. If the delay is more than ten business days, we will send you an e-mail message notifying you of the delay. If the delay will be less than ten business days, we will ship the product as soon as it is received. If your product is on backorder for more than twenty business days, we will send you an e-mail message asking if you want to cancel the order. If you do not advise us that you would like to cancel the order, we will process the order and sent it to you.</p>
<p>When your order ships, you will be provided with a tracking number via email. If you lose this email, you may call our customer service center for tracking information. We do not guarantee any specific delivery dates or times. These shipping terms are accepted by you by placing an order with us.</p>
<p><strong>RETURNS &amp; EXCHANGES</strong></p>
<p>Your first order of any one of our dietary supplements, is covered by our MAX Satisfaction money back guarantee. If for any reason you are not happy with your purchase, simply return all unused and unopened products to receive a full refund, less shipping and handling fees. Any non-supplements, or supplement orders past the initial money back guarantee, can be returned or exchanged within 30-days if they are in the original, unopened package.</p>
<p>Both policies are covered by the following terms and limitations.</p>
<p>You must return both opened and unopened product in its original packaging and have proof of purchase through this Site. Customer is responsible for return shipping. We do not accept product returns sold by third-party sellers.</p>
<p>To return a product, you must first call Omax Customer Care at 1-800-765-6691 to receive a return authorization number. We will need your order number or email address associated with your account. Any products that are refused or returned to sender will be subject to a 25% shipping and processing charge.</p>
<p>Once we receive the returned product, we will refund the purchase price less original shipping and handling fees (if any). We will notify you once your return has been received and we have issued your refund. In all cases, refunds will be given in the same form of payment as the original method of payment. Please allow up to 10 days after we have processed the refund for your bank to credit your account.</p>
<p>To make a return or exchange, please follow these steps:</p>
<ul style="margin: 0px 50px;">
<li>Obtain a Return Merchandise Authorization (RMA) number. This is required for us to process and track your return. You can obtain an RMA number by calling 1-800-765-6691 Monday – Friday between 8am and 7pm EST. Please include your order number or the email you used to place your order.</li>
<li>Include the RMA number inside the box with a copy of your packing slip or original order confirmation.</li>
<li>Ship all unopened and opened product to the Great Lakes Fulfillment address listed below. Returns sent to any othe address will not be processed. Please keep the tracking number for the return package to ensure it has been received by our warehouse.</li>
<li>Return postage is at the buyer’s expense. Any returned package sent “Return to Sender” will be subject to a 25% processing fee to cover return shipping and handling.</li>
</ul>
<p>Great Lakes Fulfillment<br /> Omax Health <br /> 41 Canal Street<br /> Lewiston, ME 04240</p>
<p><strong>SALES TAX</strong></p>
<p>Company is required by law to collect sales tax on certain orders based on appropriate state law. Your sales tax will be identified when you place your order.</p>
<p> </p>
<p><strong>PAYMENT INFORMATION</strong></p>
<p>We accept the payment methods as indicated on our Site at any particular time. To make purchases on the Site you must submit credit card information or other payment information. You represent and warrant that: (i) the credit card information you supply to us is true, correct and complete; (ii) charges incurred by you will be honored by your credit card company; and (iii) you will pay charges incurred by you at the posted prices, including all applicable taxes, if any. All payments must be in United States dollars. Current billing address, email and phone information must be included with every order. You agree to pay interest on all past-due sums at the highest rate allowed by law. We retain a security interest in the products and all proceeds thereof until the full purchase price therefore (including taxes and additional charges) has been paid. Charges for shipping and handling will be made in accordance with our then-current shipping policies, as described below. You authorize Company to use any updated credit card information submitted by your credit card company. If you dispute any charges, you must inform us within thirty (30) days of your purchase.</p>
<p><strong>PRODUCT INFORMATION</strong></p>
<p>We are constantly updating and revising our offerings of products and services, and we may discontinue products and services at any time without notice. To the extent that we provide information on availability of products or services, you should not rely on such information, and we will not be liable for any lack of availability of products or services that you may order through our site.</p>
<p>All pricing for the products and services available on our site is subject to change. For all of our prices and products, we reserve the right to make adjustments due to changing market conditions, product discontinuation, manufacturer price changes, errors in advertisements and other extenuating circumstances.</p>
<p><strong>INTERNATIONAL ORDERS</strong></p>
<p>Omax Health has partnered with a trusted third-party company, International Checkout, to fulfill orders for our international customers. Simply put the items you wish to purchase in our Shopping Cart and choose the "International Checkout" option. You will complete your order on the secure International Checkout page. You may pay by credit card, PayPal or bank transfer. International Checkout will process your order, including billing, shipping and customer service. Once you place your order, please direct all inquiries to International Checkout at <a href="mailto:support@internationalcheckout.com">support@internationalcheckout.com</a>.</p>
<p><strong>WHICH COUNTRIES DO YOU SHIP TO?</strong></p>
<p>International shipping is currently available WORLDWIDE. Our third party vendor, International Checkout, will ship to all destinations around the world including APO / FPO addresses.</p>
<p><strong>CAN I CHECK THE STATUS OF MY INTERNATIONAL ORDER?</strong></p>
<p>To check the status of your order or track your package, please login to your International Checkout account at: https://internationalcheckout.com/login.php.</p>
<p><strong>WHO SHOULD I CONTACT WITH QUESTIONS ABOUT MY INTERNATIONAL ORDER?</strong></p>
<p>All inquiries regarding your international order should be directed to International Checkout at <a href="mailto:support@internationalcheckout.com">support@internationalcheckout.com</a></p>
<p>Please visit the International Checkout Customer Service page for more information and phone numbers in your area.</p>
<p><strong>INFORMATION DISCLAIMER</strong></p>
<p>All information contained on this Site is intended as general information and should not be construed as medical advice, or used to diagnose, treat or address any medical or health problem. Always consult with a qualified healthcare professional, physician, or other medical practitioner before using dietary supplements including any of the products found on this Site.</p>
<p><strong>FORCE MAJEURE</strong></p>
<p>In addition to any excuse provided by applicable law, we shall be excused from liability for non-delivery or delay in delivery of products and service available through our site arising from any event beyond our reasonable control, whether or not foreseeable by either party, including but not limited to, labor disturbance, war, fire, accident, adverse weather, inability to secure transportation, governmental act or regulation, and other causes or events beyond our reasonable control, whether or not similar to those which are enumerated above.</p>
<p><strong>RESTRICTIONS ON USE</strong></p>
<p>The Site is protected by federal and international copyright and trademark laws. No portion of the materials on these pages may be reprinted, republished, modified, or distributed in any form without Company’s express written permission. Company reserves any rights not expressly granted by these Terms and Conditions or any applicable end user license agreements.</p>
<p><strong>SMS/MMS MOBILE MESSAGE MARKETING PROGRAM TERMS AND CONDITIONS</strong></p>
<p>Omax Health, Inc. (hereinafter, “We,” “Us,” “Our”) is offering a mobile messaging program (the “Program”), which you agree to use and participate in subject to these Mobile Messaging Terms and Conditions and Privacy Policy (the “Agreement”). By opting in to or participating in any of our Programs, you accept and agree to these terms and conditions, including, without limitation, your agreement to resolve any disputes with us through binding, individual-only arbitration, as detailed in the “Dispute Resolution” section below. This Agreement is limited to the Program and is not intended to modify other Terms and Conditions or Privacy Policy that may govern the relationship between you and Us in other contexts.</p>
<p><strong>User Opt In:</strong> The Program allows Users to receive SMS/MMS mobile messages by affirmatively opting into the Program, such as through online or application-based enrollment forms. Regardless of the opt-in method you utilized to join the Program, you agree that this Agreement applies to your participation in the Program. By participating in the Program, you agree to receive autodialed or prerecorded marketing mobile messages at the phone number associated with your opt-in, and you understand that consent is not required to make any purchase from Us. While you consent to receive messages sent using an autodialer, the foregoing shall not be interpreted to suggest or imply that any or all of Our mobile messages are sent using an automatic telephone dialing system (“ATDS” or “autodialer”). Message and data rates may apply.</p>
<p><strong>User Opt Out:</strong> If you do not wish to continue participating in the Program or no longer agree to this Agreement, you agree to reply STOP, END, CANCEL, UNSUBSCRIBE, or QUIT to any mobile message from Us in order to opt out of the Program. You may receive an additional mobile message confirming yourdecision to opt out. You understand and agree that the foregoing options are the only reasonable methods of opting out. You also understand and agree that any other method of opting out, including, but not limited to, texting words other than those set forth above or verbally requesting one of our employees to remove you from our list, is not a reasonable means of opting out.</p>
<p><strong>Duty to Notify and Indemnify:</strong> If at any time you intend to stop using the mobile telephone number that has been used to subscribe to the Program, including canceling your service plan or selling or transferring the phone number to another party, you agree that you will complete the User Opt Out process set forth above prior to ending your use of the mobile telephone number. You understand and agree that your agreement to do so is a material part of these terms and conditions. You further agree that, if you discontinue the use of your mobile telephone number without notifying Us of such change, you agree that you will be responsible for all costs (including attorneys’ fees) and liabilities incurred by Us, or any party that assists in the delivery of the mobile messages, as a result of claims brought by individual(s) who are later assigned that mobile telephone number. This duty and agreement shall survive any cancellation or termination of your agreement to participate in any of our Programs. YOU AGREE THAT YOU SHALL INDEMNIFY, DEFEND, AND HOLD US HARMLESS FROM ANY CLAIM OR LIABILITY RESULTING FROM YOUR FAILURE TO NOTIFY US OF A CHANGE IN THE INFORMATION YOU HAVE PROVIDED, INCLUDING ANY CLAIM OR LIABILITY UNDER THE TELEPHONE CONSUMER PROTECTION ACT, 47 U.S.C. § 227, et seq., OR SIMILAR STATE AND FEDERAL LAWS, AND ANY REGULATIONS PROMULGATED THEREUNDER RESULTING FROM US ATTEMPTING TO CONTACT YOU AT THE MOBILE TELEPHONE NUMBER YOU PROVIDED.</p>
<p><strong>Program Description:</strong> Without limiting the scope of the Program, users that opt into the Program can expect to receive messages concerning the marketing and sale of Omax Health’s products.</p>
<p><strong>Cost and Frequency:</strong> Message and data rates may apply. The Program involves recurring mobile messages, and additional mobile messages may be sent periodically based on your interaction with Us. Support Instructions: For support regarding the Program, text “HELP” to the number you received messages from or email us at <a href="care@omaxhealth.com">care@omaxhealth.com</a>. Please note that the use of this email address is not an acceptable method of opting out of the program. Opt outs must be submitted in accordance with the procedures set forth above.</p>
<p><strong>MMS Disclosure:</strong> The Program will send SMS TMs (terminating messages) if your mobile device does not support MMS messaging. Our Disclaimer of Warranty: The Program is offered on an "as-is" basis and may not be available in all areas at all times and may not continue to work in the event of product, software, coverage or other changes made by your wireless carrier. We will not be liable for any delays or failures in the receipt of any mobile messages connected with this Program. Delivery of mobile messages is subject to effective transmission from your wireless service provider/network operator and is outside of Our control. T-Mobile is not liable for delayed or undelivered mobile messages.</p>
<p><strong>Participant Requirements:</strong> You must have a wireless device of your own,capable of two-way messaging, be using a participating wireless carrier, andbe a wireless service subscriber with text messaging service. Not all cellularphone providers carry the necessary service to participate. Check yourphone capabilities for specific text messaging instructions.</p>
<p><strong>Age Restriction:</strong> You may not use of engage with the Platform if you areunder thirteen (13) years of age. If you use or engage with the Platform andare between the ages of thirteen (13) and eighteen (18) years of age, youmust have your parent’s or legal guardian’s permission to do so. By using orengaging with the Platform, you acknowledge and agree that you are notunder the age of thirteen (13) years, are between the ages of thirteen (13)and eighteen (18) and have your parent’s or legal guardian’s permission touse or engage with the Platform, or are of adult age in your jurisdiction. Byusing or engaging with the Platform, you also acknowledge and agree thatyou are permitted by your jurisdiction’s Applicable Law to use and/or engagewith the Platform.</p>
<p><strong>Prohibited Content:</strong> You acknowledge and agree to not send any prohibitedcontent over the Platform. Prohibited content includes:</p>
<ul style="margin: 0px 50px;">
<li>Any fraudulent, libelous, defamatory, scandalous, threatening,harassing, or stalking activity;</li>
<li>Objectionable content, including profanity, obscenity, lasciviousness,violence, bigotry, hatred, and discrimination on the basis of race, sex,religion, nationality, disability, sexual orientation, or age;</li>
<li>Pirated computer programs, viruses, worms, Trojan horses, or otherharmful code;</li>
<li>Any product, service, or promotion that is unlawful where such product,service, or promotion thereof is received;</li>
<li>Any content that implicates and/or references personal healthinformation that is protected by the Health Insurance</li>
<li>Portability andAccountability Act (“HIPAA”) or the Health Information Technology forEconomic and Clinical Health Act (“HITEC” Act);</li>
<li>Any other content that is prohibited by Applicable Law in the jurisdiction from which the message is sent.</li>
</ul>
<p><strong>Dispute Resolution:</strong> In the event that there is a dispute, claim, or controversy between you and Us, or between you and Stodge, LLC d/b/a Postscript or any other third-party service provider acting on Our behalf to transmit the mobile messages within the scope of the Program, arising out of or relating tofederal or state statutory claims, common law claims, this Agreement, or thebreach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, such dispute, claim, or controversy will be, to the fullest extent permitted bylaw, determined by arbitration in Santa Monica, CA before one arbitrator.</p>
<p>The parties agree to submit the dispute to binding arbitration in accordancewith the Commercial Arbitration Rules of the American ArbitrationAssociation (“AAA”) then in effect. Except as otherwise provided herein, thearbitrator shall apply the substantive laws of the Federal Judicial Circuit inwhich Omax Health’s principle place of business is located, without regard toits conflict of laws rules. Within ten (10) calendar days after the arbitrationdemand is served upon a party, the parties must jointly select an arbitratorwith at least five years’ experience in that capacity and who has knowledgeof and experience with the subject matter of the dispute. If the parties donot agree on an arbitrator within ten (10) calendar days, a party may petition the AAA to appoint an arbitrator, who must satisfy the same experiencerequirement. In the event of a dispute, the arbitrator shall decide theenforceability and interpretation of this arbitration agreement in accordancewith the Federal Arbitration Act (“FAA”). The parties also agree that theAAA’s rules governing Emergency Measures of Protection shall apply in lieuof seeking emergency injunctive relief from a court. The decision of thearbitrator shall be final and binding, and no party shall have rights of appealexcept for those provided in section 10 of the FAA. Each party shall bear itsshare of the fees paid for the arbitrator and the administration of thearbitration; however, the arbitrator shall have the power to order one partyto pay all or any portion of such fees as part of a well-reasoned decision. The parties agree that the arbitrator shall have the authority to award attorneys’fees only to the extent expressly authorized by statute or contract. Thearbitrator shall have no authority to award punitive damages and each partyhereby waives any right to seek or recover punitive damages with respect toany dispute resolved by arbitration. The parties agree to arbitrate solely onan individual basis, and this agreement does not permit class arbitration orany claims brought as a plaintiff or class member in any class orrepresentative arbitration proceeding. Except as may be required by law,neither a party nor the arbitrator may disclose the existence, content, orresults of any arbitration without the prior written consent of both parties,unless to protect or pursue a legal right. If any term or provision of thisSection is invalid, illegal, or unenforceable in any jurisdiction, such invalidity,illegality, or unenforceability shall not affect any other term or provision ofthis Section or invalidate or render unenforceable such term or provision inany other jurisdiction. If for any reason a dispute proceeds in court ratherthan in arbitration, the parties hereby waive any right to a jury trial. Thisarbitration provision shall survive any cancellation or termination of youragreement to participate in any of our Programs.</p>
<p><strong>Miscellaneous:</strong> You warrant and represent to Us that you have all necessaryrights, power, and authority to agree to these Terms and perform yourobligations hereunder, and nothing contained in this Agreement or in theperformance of such obligations will place you in breach of any othercontract or obligation. The failure of either party to exercise in any respectany right provided for herein will not be deemed a waiver of any furtherrights hereunder. If any provision of this Agreement is found to beunenforceable or invalid, that provision will be limited or eliminated to theminimum extent necessary so that this Agreement will otherwise remain infull force and effect and enforceable. Any new features, changes, updates orimprovements of the Program shall be subject to this Agreement unlessexplicitly stated otherwise in writing. We reserve the right to change thisAgreement from time to time. Any updates to this Agreement shall becommunicated to you. You acknowledge your responsibility to review thisAgreement from time to time and to be aware of any such changes. Bycontinuing to participate in the Program after any such changes, you acceptthis Agreement, as modified.</p>
<p><strong>TRADEMARK AND PATENTS</strong></p>
<p>Omax®, Omax3®, and The Ultra-Pure Omega-3 Supplement™, whether or not appearing in capital letters, bold typeface, or with the trademark symbol, are registered trademarks of Company and may not be used without permission. Use, reproduction, copying, or redistribution of these trademarks, without written permission is prohibited. The use or misuse of these trademarks, copyrights, or other materials is expressly prohibited and may be in violation of copyright law, trademark law, communications regulations and statutes, and other laws, statutes, and/or regulations. Omax3 is protected by U.S. patents #7,652,068 and 8,071,646.</p>
<p><strong>WARRANTY DISCLAIMER</strong></p>
<p>ALL PRODUCTS AND SERVICES AVAILABLE ON THIS SITE ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR THE WARRANT OF NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, WE MAKE NO WARRANTY THAT THE PRODUCTS AND SERVICES AVAILABLE ON THIS SITE WILL MEET YOUR REQUIREMENTS; THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE PRODUCTS OR SERVICES WILL BE EFFECTIVE, ACCURATE OR RELIABLE; OR THE QUALITY OF ANY PRODUCTS OR SERVICES WILL MEET YOUR EXPECTATIONS. SOME JURISDICTIONS LIMIT OR DO NOT ALLOW THE DISCLAIMER OF IMPLIED OR OTHER WARRANTIES SO THE ABOVE DISCLAIMER MAY NOT APPLY TO THE EXTENT SUCH JURISDICTION’S LAW IS APPLICABLE TO YOUR PURCHASE OF PRODUCTS AND SERVICES. WE DO NOT ACCEPT LIABILITY BEYOND THE REMEDIES SET FORTH HEREIN, INCLUDING ANY LIABILITY FOR PRODUCTS AND SERVICES THAT ARE NOT AVAILABLE FOR USE OR FOR LOST OR CORRUPTED DATA OR SOFTWARE. IN NO EVENT SHALL WE OR OUR PARENT, SUBSIDIARIES, AFFILIATED COMPANIES, AGENTS, SHAREHOLDERS, EMPLOYEES, OR OFFICERS (COLLECTIVELY, OUR “AFFILIATES”) HAVE ANY OBLIGATIONS OR LIABILITIES TO YOU OR ANY OTHER PERSON FOR LOSS OF PROFITS, FOR LOSS OF BUSINESS OR USE, OR FOR INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, WHETHER BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR ANY OTHER THEORY OR FORM OF ACTION, EVEN IF WE OR OUR AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY THEREOF, ARISING OUT OR IN CONNECTION WITH THE SALE, DELIVERY, USE, REPAIR OR PERFORMANCE OF THE PRODUCTS AVAILABLE THROUGH THIS SITE. NONE OF OUR EMPLOYEES OR REPRESENTATIVES ARE AUTHORIZED TO MODIFY THIS LIMITATION. OUR SOLE AND ENTIRE MAXIMUM LIABILITY (AND THE LIABILITY OF ANY OF THE PROVIDERS OF PRODUCTS AND SERVICES AVAILABLE ON OUR SITE), FOR ANY REASON, AND YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY CAUSE WHATSOEVER, SHALL BE LIMITED TO THE ACTUAL AMOUNT PAID BY YOU FOR THE PRODUCTS AND SERVICES YOU HAVE ORDERED THROUGH OUR SITE. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU TO THE EXTENT SUCH JURISDICTION’S LAW IS APPLICABLE TO YOUR PURCHASE OF PRODUCTS AND SERVICES.</p>
<p>Although Company attempts to ensure the integrity and accurateness of the Site, it makes no guarantees whatsoever as to the correctness or accuracy of the Site. It is possible that the Site could include inaccuracies or errors, and that unauthorized additions, deletions and alterations could be made to the Site by third parties. In the event that an inaccuracy arises, please inform Company so that it can be corrected. Information contained on the Site may be changed or updated without notice.</p>
<p><strong>LINKS OR POINTERS TO OTHER SITES</strong></p>
<p>Company makes no representations whatsoever about any other Website that you may access though this Site. When you access a non-Company Website, please understand that it is independent from Company and this Site, and that Company has no control over the content on that Website. In addition, a hyperlink to a non-Company Website does not mean that Company endorses or accepts any responsibility for the content, or the use, of the linked site. It is up to you to take precautions to ensure that whatever you select for your use or download is free of such items as viruses, worms, trojan horses, and other items of a destructive nature.</p>
<p><strong>DISPUTE RESOLUTIONS</strong></p>
<strong>Governing Law</strong><br />
<p>Use of the Site or purchases made through the Site, and any controversy, claim or dispute arising out of or relating in any way to Company’s products or services shall be governed by the laws of the state of New Jersey without respect to its choice (or conflict) of laws rules. Any claim or cause of action must be filed in New Jersey as set forth herein. In any arbitration or other dispute brought against Company, the prevailing party will be awarded its costs and attorneys’ fees.</p>
<p>Any claim or cause of action you may have with respect to the Site or Company must be commenced within one (1) year after the claim or cause of action arose. Failure to make a claim or cause of action within the one year period will result in forfeiture of your right to make such a claim or cause of action except where prohibited by law.</p>
<p><strong>Agreement to Arbitrate Claims</strong></p>
<p>You acknowledge and agree to the terms of an Arbitration Agreement by accessing or using this Site, mobile application or by using any other Company product or service. The Arbitration Agreement is incorporated into these Terms and Conditions as though set forth in full herein. You acknowledge that you have reviewed and agree to Company’s Privacy Policy, which can be accessed here (“Privacy Policy”). The Privacy Policy is incorporated by reference to these Terms and Conditions as though set forth in full herein.</p>
<p><strong>GENERAL INFORMATION</strong></p>
<p>These Terms and Conditions govern your use of the Site and any of Company’s products and services. Company’s failure to exercise or enforce any right or provision of these Terms and Conditions shall not constitute a waiver of such right or provision. The invalidity of any term, condition or provision in these Terms and Conditions shall not affect the enforceability of those portions of the Terms and Conditions deemed enforceable by applicable courts of law.</p>
<p><strong>ENTIRE AGREEMENT</strong></p>
<p>These Terms and Conditions constitute the entire agreement between Company and you pertaining to the subject matter of these Terms and Conditions. In its sole discretion, Company may modify these Terms and Conditions by posting the revised version on this Site and you agree that each visit by you to this Site is a new transaction governed by the terms of use linked on this Site at that time.</p>
<p><strong>NO UNLAWFUL OR PROHIBITED PURPOSE</strong></p>
<p>As a condition of your use of this Site, you warrant to Company that you will not use the Site for any purpose that is unlawful or prohibited by these Terms and Conditions.</p>
<p><strong>ARBITRATION AGREEMENT</strong></p>
<p>This website and all pages within this website located at <a href="https://omaxsleep.com" target="_blank">omaxsleep.com</a> (this "Site") and Omax Health, Inc. f/k/a Prevention Pharmaceuticals, Inc. (“Company”) together provide website features and other products and services when you visit, shop or purchase from this site. This Arbitration Agreement affects your legal rights and remedies, and provides that all disputes between you and Company must be resolved through, mandatory, binding arbitration as specified herein rather than through a lawsuit by any other means, except as otherwise provided. If you do not agree to the Arbitration Agreement, please do not use this Site or any Omax Health product. Resolution of claims or disputes.</p>
<p>Any claim or dispute between you and Company arising out of or relating in any way to the Product, the Site or this Agreement shall be resolved through final, binding arbitration. This mandatory arbitration obligation applies regardless of whether the claim or dispute involves a tort, fraud, misrepresentation, product liability, negligence, violation of a statute, or any other legal theory. Both you and the Company acknowledge and agree that you waive your right to bring a lawsuit based on such claims or disputes and that you waive your right to have such claims or disputes resolved by a judge or jury. Notwithstanding the foregoing, you have the right to seek relief in small claims court for claims or disputes within the scope of small claims jurisdictional limits. Limitation of legal remedies.</p>
<p>All arbitrations under this Agreement shall be conducted on an individual (and not a class-wide) basis, and an arbitrator shall have no authority to award class-wide relief. You acknowledge and agree that this Agreement specifically prohibits you from commencing arbitration proceedings as a representative of others or joining in any arbitration, litigation or other proceeding brought by any other person. Arbitration procedures.</p>
<ol style="margin: 0px 50px;">
<li>Before commencing any arbitration proceedings under this Agreement, you must first present the claim or dispute to the Company by sending a written complaint to Company, Attn: Legal Department, 2601 Ocean Park Blvd., Santa Monica, CA, 90405, and allowing the Company the opportunity to resolve the claim or dispute. If your claim or dispute is not resolved within sixty (60) days, you may commence arbitration proceedings in accordance with the terms of this Agreement.</li>
<li>The arbitration of any claim or dispute under this Agreement shall be conducted pursuant to the American Arbitration Association's ("AAA") United States Commercial Dispute Resolution Procedures and Supplementary Procedures for Consumer-Related Disputes. These rules and procedures are available at <a href="https://adr.org/Rules" target="_blank" rel="noopener noreferrer">https://adr.org/Rules.</a></li>
<li>The arbitration of any claim or dispute under this Agreement shall be conducted in the State of New Jersey, in the city of Princeton.</li>
<li>The arbitration of any claim or dispute under this Agreement shall be conducted by an arbitrator who is independent and impartial. The exchange of information and timing of the arbitration shall be supervised by the arbitrator and shall be in accordance with procedures provided by the arbitrator.</li>
<li>Unless either party or the arbitrator requests a hearing, the parties will submit their arguments and evidence to the arbitrator in writing. The arbitrator will make an award based only on the documents. This is called a Desk Arbitration. If any party makes a written request for a hearing within ten days after the American Arbitration Association acknowledges receipt of a claimant's demand for arbitration (or the arbitrator requests a hearing), the parties shall participate in telephonic hearing.</li>
<li>If you decide to commence arbitration, the provider will require to you to pay a filing fee (which currently is $125 for claims under $10,000). If your filing fee is more than $125, The Company will reimburse you for any excess fee promptly after it receives notice of your arbitration.</li>
</ol>
<p><strong>Choice of law</strong></p>
<p>This Agreement shall be governed by the United States Federal Arbitration Act and the laws of the state of New Jersey.</p>
<p><strong>Severability</strong></p>
<p>If any provision of this Agreement is declared or found to be unlawful, unenforceable or void, such provision will be ineffective only to the extent that is found unlawful, unenforceable or void, and the remainder of the provision and all other provisions shall remain fully enforceable.</p>
<p><strong>Waiver of damages</strong></p>
<p>Each of the parties hereby (a) irrevocably waives, to the maximum extent not prohibited by law, any right it may have to a trial by jury in respect of any proceeding directly or indirectly at any time arising out of, under or in connection with the purchase of the Product from Company or any transaction contemplated hereby or associated herewith; (b) irrevocably waives, to the maximum extent not prohibited by law, any right it may have to claim or recover in any such proceeding any special, exemplary, punitive or consequential damages, or any damages other than, or in addition to, actual damages.</p>
<p>Omax Health, Inc.<br /> 2601 Ocean Park Blvd, Ste 214<br /> Santa Monica, CA 90405<br /> USA</p>
<p><strong>QUESTIONS AND CONTACT INFORMATION</strong></p>
<p><a href="mailto:care@omaxhealth.com">care@omaxhealth.com</a><br /> 1-800-765-6691 (M-F, 8am to 7pm EST)</p>
<p>© Omax Health, Inc. <script>document.write(new Date().getFullYear())</script></p>
<p> </p>
<p> </p>
		</div>
</main>

<?php get_template_part('block','footer'); ?>